### ISSUE TITLE
Configurar CNAME

### ISSUE THREAD

**Issue by jsanz** [geocamp-es/2017#2]
@olea supongo que alguien de organización de años anteriores tiene que apuntar a este repo en la configuración del dominio

**Comment by fpsampayo** [comment]
En principio todo funciona bien, pero Github me da unos avisos de que cambie la redirección a geoinquietos-org.github.io. Voy a cambiarlo y si queda todo OK cierro la issue.

**Comment by fpsampayo** [comment]
Ala, listo!

**Comment by jsanz** [comment]
Ole

--
Jorge Sanz
